Includes = ../
CXX = g++
CFLAGS = -std=c++17 -g

# Libs=#whatever libraries you need to provide to g++

DocumentInterface.o:DocumentInterface.cpp
	$(CXX) $(CFLAGS) -I $(Includes) -c -o ../DocumentInterface.o DocumentInterface.cpp 

clean:
	rm *.o
